name: Fit Wellness Centers
favicon: null
layout_spectrum: 0.7234157
typography_spectrum: 0.55768
title: "Seattle's Premier Wellness Center for Health & Fitness"
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#192857'
    - '#a9a9aa'
    - '#56565b'
    - '#ffffff'
    - '#000000'
  brandStrength: 0.2989025304559618
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
