name: Fit Wellness Centers
favicon: null
layout_spectrum: 0.42615372384898365
typography_spectrum: 0.22549218963831663
title: Fit Wellness Centers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.2989025304559618
  lightness: 0.6644905123393983
  saturation: 0.30447318335063756
  rhythmicContrast: 0.5576105949003249
purpose: []
