title: "Seattle's Premier Wellness Center for Health & Fitness"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3044732
  brandStrength: 0.2989025304559618
  lightness: 1
  brandColors:
    - '#192857'
    - '#a9a9aa'
    - '#56565b'
    - '#ffffff'
    - '#000000'
  rhythmicContrast: 0.5576106
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Fit Wellness Centers
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.55768
layout_spectrum: 0.7234157
