name: Fit Wellness Centers
favicon: null
layout_spectrum: 0.18746
typography_spectrum: 0.22549218963831663
title: "Seattle's Premiere Wellness Center for Health & Fitness"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#192857'
    - '#a9a9aa'
    - '#56565b'
    - '#ffffff'
    - '#000000'
  brandStrength: 0.2989025304559618
  lightness: 0.6644905123393983
  saturation: 0.30447318335063756
  rhythmicContrast: 0.5576105949003249
purpose: []
